dist: bionic
language: java
jdk: openjdk8

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

stages:
  - name: test
  - name: deploy
    if: type != pull_request

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      after_success:
      - bash <(curl -s https://codecov.io/bash)

    - stage: deploy
      name: "Release"
      script: ./gradlew ciPerformRelease
      if: tag =~ /^release\/v.[\d\.]+(\-.*)?$/
